config/routes.rb
Rails.application.routes.draw do
  root "tinyurls#index"
  get 'catch_all/index'
  resources :tinyurls
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '*path', to: 'catch_all#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tinyurl.rb
class Tinyurl < ApplicationRecord
    validates :tiny_url, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
end

app/controllers/catch_all_controller.rb
class CatchAllController < ApplicationController
  def index
    # Get the requested tiny url and redirect to it (if not works, shows an error)
    url = Tinyurl.find_by(tiny_url: request.fullpath.remove("/"))
    unless url 
      render html: ("<h1>Url: <br/> http://#{request.host}:#{request.port}"+request.fullpath+" <br/>not found.</h1>").html_safe
    else
      unless url.expiration > DateTime.now
        render html: ("<h1>Url: <br/> http://#{request.host}:#{request.port}"+request.fullpath+" <br/>expired.</h1>").html_safe
      else
        url.increment(:used_count)
        url.save
        redirect_to url.original_url
      end
    end
    
  end
end

app/controllers/tinyurls_controller.rb
class TinyurlsController < ApplicationController
  before_action :set_tinyurl, only: [:show, :edit, :update, :destroy]

  # GET /tinyurls
  # GET /tinyurls.json
  def index
    @tinyurls = Tinyurl.all
  end

  # GET /tinyurls/1
  # GET /tinyurls/1.json
  def show
  end

  # GET /tinyurls/new
  def new
    # Call library to generate random strings
    require 'securerandom'
    @tinyurl = Tinyurl.new
    # Prepopulate the random string
    @tinyurl.tiny_url = SecureRandom.urlsafe_base64(5)
    #@tinyurl.expiration += 50
    puts DateTime.now
  end

  # GET /tinyurls/1/edit
  def edit
  end

  # POST /tinyurls
  # POST /tinyurls.json
  def create
    @tinyurl = Tinyurl.new(tinyurl_params)

    respond_to do |format|
      if @tinyurl.save
        format.html { redirect_to @tinyurl, notice: 'Tinyurl was successfully created.' }
        format.json { render :show, status: :created, location: @tinyurl }
      else
        format.html { render :new }
        format.json { render json: @tinyurl.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tinyurls/1
  # PATCH/PUT /tinyurls/1.json
  def update
    respond_to do |format|
      if @tinyurl.update(tinyurl_params)
        format.html { redirect_to @tinyurl, notice: 'Tinyurl was successfully updated.' }
        format.json { render :show, status: :ok, location: @tinyurl }
      else
        format.html { render :edit }
        format.json { render json: @tinyurl.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tinyurls/1
  # DELETE /tinyurls/1.json
  def destroy
    @tinyurl.destroy
    respond_to do |format|
      format.html { redirect_to tinyurls_url, notice: 'Tinyurl was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tinyurl
      @tinyurl = Tinyurl.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tinyurl_params
      params.require(:tinyurl).permit(:original_url, :tiny_url, :expiration)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/catch_all_helper.rb
module CatchAllHelper
end

app/helpers/tinyurls_helper.rb
module TinyurlsHelper
end

app/views/catch_all/index.html.erb
<h1>CatchAll#index</h1>
<p>Find me in app/views/catch_all/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Grtest</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tinyurls/_form.html.erb
<%= form_with(model: tinyurl, local: true) do |form| %>
  <% if tinyurl.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tinyurl.errors.count, "error") %> prohibited this tinyurl from being saved:</h2>

      <ul>
      <% tinyurl.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :original_url %>
    <%= form.text_field :original_url %>
  </div>

  <div class="field">
    <%= form.label :tiny_url %>
    <%= "http://#{request.host}:#{request.port}/" %><%= form.text_field :tiny_url %>
  </div>

  <div class="field">
    <%= form.label :expiration %>
    <%= form.datetime_select :expiration, :default=> DateTime.now+5 %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tinyurls/edit.html.erb
<h1>Editing Tinyurl</h1>

<%= render 'form', tinyurl: @tinyurl %>

<%= link_to 'Show', @tinyurl %> |
<%= link_to 'Back', tinyurls_path %>

app/views/tinyurls/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tinyurls</h1>

<table>
  <thead>
    <tr>
      <th>Original url</th>
      <th>Tiny url</th>
      <th>Expiration</th>
      <th>Used count</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tinyurls.each do |tinyurl| %>
      <tr>
        <td><%= tinyurl.original_url %></td>
        <td><%= tinyurl.tiny_url %></td>
        <td><%= tinyurl.expiration %></td>
        <td><%= tinyurl.used_count %></td>
        <td><%= link_to 'Show', tinyurl %></td>
        <td><%= link_to 'Edit', edit_tinyurl_path(tinyurl) %></td>
        <td><%= link_to 'Destroy', tinyurl, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tinyurl', new_tinyurl_path %>

<br />
<br />
<br />

<h1><a id="Supuestos_0"></a>Supuestos</h1>
<h2><a id="Requerimientos_funcionales_2"></a>Requerimientos funcionales:</h2>
<ul>
<li>
<p>Dada una URL, nuestro servicio debe generar un alias más corto y único. Esto se llama un enlace corto. <code>http://localhost:3000/tinyurls</code></p>
</li>
<li>
<p>Cuando los usuarios acceden a un enlace corto, nuestro servicio debería redirigirlos al enlace original. <code>http://localhost:3000/&lt;enlace corto&gt;</code></p>
</li>
<li>
<p>Los usuarios, opcionalmente, deberían poder elegir un enlace corto personalizado para sus URL. <code>Campo abierto para poder ser editado (validado por si hay repetidos)</code></p>
</li>
<li>
<p>Los enlaces caducarán después de un intervalo de tiempo predeterminado estándar. Los usuarios deben poder especificar el tiempo de caducidad. <code>El tiempo predeterminado es de 5 días después. Validacion de url expirada.</code></p>
</li>
</ul>
<h2><a id="Requerimientos_no_funcionales_12"></a>Requerimientos no funcionales:</h2>
<ul>
<li>La redirección de URL debería ocurrir en tiempo real con una latencia mínima. <code>La condición está en el redirect. Me hubiera gustado usar redis para mantener en cache las urls pero por tiempo ya no lo implementé</code></li>
<li>Los enlaces acortados no deben ser adivinables (no predecibles).</li>
</ul>
<h2><a id="Requisitos_extendidos_puntos_extra_17"></a>Requisitos extendidos (puntos extra):</h2>
<ul>
<li>Analítica; Por ejemplo, ¿cuántas veces sucedió una redirección? <code>Incluido contador de redirecciones</code></li>
<li>Nuestro servicio también debe ser accesible a través de una simple API REST (sin autenticación) por otros servicios. <code>Rails expone los servicios RESTful de forma predeterminada para poder ser consumidos como API. Usar 'rake routes' para saber las rutas del API.</code></li>
</ul>

app/views/tinyurls/new.html.erb
<h1>New Tinyurl</h1>

<%= render 'form', tinyurl: @tinyurl %>

<%= link_to 'Back', tinyurls_path %>

app/views/tinyurls/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Original url:</strong>
  <a target="_blank" rel="noopener noreferrer"  href='<%= @tinyurl.original_url %>'><%= @tinyurl.original_url %></a>
</p>

<p>
  <strong>Tiny url:</strong>
  <a target="_blank" rel="noopener noreferrer"  href='<%= "http://#{request.host}:#{request.port}/" %><%= @tinyurl.tiny_url %>'><%= "http://#{request.host}:#{request.port}/" %><%= @tinyurl.tiny_url %></a>
</p>

<p>
  <strong>Expiration:</strong>
  <%= @tinyurl.expiration %>
</p>

<p>
  <strong>Used count:</strong>
  <%= @tinyurl.used_count %>
</p>

<%= link_to 'Edit', edit_tinyurl_path(@tinyurl) %> |
<%= link_to 'Back', tinyurls_path %>